name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  update-wakatime:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download WakaTime stats badge
      run: |
        curl -o wakatime.svg https://wakatime.com/share/@Suresh1/your-actual-project/stats.svg

    - name: Commit and push updated badge
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add wakatime.svg
        git commit -m "Update WakaTime stats badge" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
