name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch GitHub stats image
        run: |
          curl -H "Authorization: token ${{ secrets.STATUS }}" \
          "https://github-readme-stats.vercel.app/api?username=Suresh-Shrestha1&show_icons=true&theme=radical" \
          -o stats.svg

      - name: Commit and push updated stats image
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add stats.svg
          git commit -m "Update GitHub stats"
          git push
        continue-on-error: true  # To avoid failing if no changes
